include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI interface for Truba
LUCI_DEPENDS:=+truba +luci-base
LUCI_PKGARCH:=all

PKG_LICENSE:=Apache-2.0
PKG_VERSION:=1.0.0
PKG_RELEASE:=1

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
